name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      node_version:
        description: "Chose the node version to deploy"
        required: true
        type: choice
        options: ["18", "20"]
        default: "18"
      environment:
        description: "Select the environment to deploy to"
        required: true
        type: choice
        options: ["dev", "pre-prod", "production"]
        default: "dev"

env:
  RUNS_ON: ubuntu-latest

jobs:
  printInputs:
    runs-on: $RUNS_ON
    steps:
      - run: |
          echo "node version: ${{ github.event.inputs.node_version }}"
          echo "environment: ${{ github.event.inputs.environment }}"
  build:
    runs-on: $RUNS_ON
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set Node version
        uses: actions/setup-node@master
        with:
          node-version: ${{ github.event.inputs.node_version }}

      - name: Install and Build
        run: |
          yarn && yarn run build

  deploy:
    runs-on: $RUNS_ON

    steps:
      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: build
