name: Deploy to Netlify

on:
  push:
    branches: master
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [dev, prod]
        default: dev
permissions:
  security-events: write
  actions: read
  contents: read
  issues: write

jobs:
  CodeScan:
    uses: aoda-zhang/shared-devops/.github/workflows/code_scan.yaml@master
    with:
      app_repository: ${{ github.repository }}

  Build_Deploy:
    needs: CodeScan
    uses: aoda-zhang/shared-devops/.github/workflows/deploy_netlify.yaml@master
    with:
      app_repository: ${{ github.repository }}
      config_folder: honey-frontEnd
      currentEnv: ${{ inputs.environment }}
    secrets:
      PAT: ${{ secrets.CONFIG_ACCESS_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
