name: Deploy to Vercel(NO PROD)

on:
  push:
    branches: [develop, master]
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [dev, test]
        default: dev
permissions:
  security-events: write
  actions: read
  contents: read

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_USER_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  CodeScan:
    uses: aoda-zhang/shared-devops/.github/workflows/code_scan.yaml@master
    with:
      repository: ${{ github.repository }}
    secrets: inherit

  SetEnvironment:
    needs: CodeScan
    uses: aoda-zhang/shared-devops/.github/workflows/setEnvironment.yaml@master
    with:
      config_folder: honey-frontEnd
      currentEnv: ${{ inputs.environment }}
    secrets:
      PAT: ${{ secrets.CONFIG_ACCESS_TOKEN }}

  Build_and_Deploy_Dev:
    needs: SetEnvironment
    runs-on: ubuntu-latest
    steps:
      - name: show env
        run: cat $GITHUB_ENV
      - name: Checkout business code
        uses: actions/checkout@master

      - name: Install
        run: |
          yarn
          yarn global add vercel@latest

      - name: Build Project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
