name: Deploy to AWS S3

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Display environment variables
        run: |
          echo "BUCKET: ${{secrets.AWS_S3_BUCKET}}" >> secrets.txt
          echo "AWS_KEY_ID: ${{secrets.AWS_KEY_ID}}" >> secrets.txt
          echo "AWS_SECRET_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}" >> secrets.txt

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn

      - name: Build site
        run: npm run build

      - name: deploy code
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "arn:aws:s3:ap-northeast-1:533267178560:accesspoint/honey-app"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          SOURCE_DIR: "build"

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
