name: Deploy to AWS S3 (NO PROD)

on:
  push:
    branches: [develop, master]
    paths-ignore:
      - "**/.github/**"
      - "**/*.txt"
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy"
        required: true
        type: choice
        options: [dev, test]
        default: dev
permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  CodeScan:
    uses: aoda-zhang/shared-devops/.github/workflows/code_scan.yaml@master
    with:
      repository: ${{ github.repository }}
    secrets: inherit

  Build:
    uses: aoda-zhang/shared-devops/.github/workflows/shared_build.yaml@master
    with:
      app_repository: ${{ github.repository }}
      config_folder: honey-frontEnd
      currentEnv: ${{ inputs.environment }}
      build_name: build-artifacts
    secrets:
      PAT: ${{ secrets.CONFIG_ACCESS_TOKEN }}

  Deploy:
    uses: aoda-zhang/shared-devops/.github/workflows/deploy_aws_s3.yaml@master
    needs: Build
    with:
      build_name: build-artifacts
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
